version: "3.8"
services:
  nexus:
    image: sonatype/nexus3:3.82.0
    restart: always
    volumes:
      - "nexus-data:/sonatype-work"
    ports:
      - "8081:8081"
      - "8085:8085"
volumes:
  nexus-data: {}
