version: "3"

services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data/mysql-data:/var/lib/mysql
    networks:
      - internal
  
  drupal:
    image: drupal:10.0.9-fpm-alpine3.18
    container_name: drupal
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - internal
      - external
    volumes:
      - ./data/drupal-data:/var/www/html
  
  webserver:
    image: nginx:1.25.1-alpine-slim
    container_name: webserver
    depends_on:
      - drupal
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./data/drupal-data:/var/www/html
      - ./data/nginx-data:/etc/nginx/conf.d
      - ./certbot-data:/etc/letsencrypt
    networks:
      - external
  
  certbot:
    depends_on:
      - webserver
    image: certbot/certbot:v2.3.0
    container_name: certbot
    volumes:
      - ./certbot-data:/etc/letsencrypt
      - ./data/drupal-data:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email sammy@your_domain --agree-tos --no-eff-email --staging -d localhost

networks:
  external:
    driver: bridge
  internal:
    driver: bridge