name: activemq-artemis
services:
  activemq-artemis:
    container_name: activemq-artemis
    image: apache/activemq-artemis:2.41.0-alpine
    environment:
      ARTEMIS_USERNAME: admin
      ARTEMIS_PASSWORD: admin
    ports:
      - "61616:61616" # Core Protocol (TCP)
      - "61613:61613" # STOMP
      - "1883:1883" # MQTT
      - "5672:5672" # AMQP
      - "8161:8161" # Web Console (HTTP)
      - "1099:1099" # JMX RMI Registry Port
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8161 || exit 1
      interval: 1m
      timeout: 1s
      retries: 3
