services:
  grafana:
    container_name: grafana
    image: grafana/grafana:12.0.1
    # volumes:
    #   - grafana_data:/var/lib/grafana
    #   - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    #   - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - 3000:3000
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--tries=1",
          "--spider",
          "--quiet",
          "http://localhost:3000/api/health",
        ]
      interval: 1m
      timeout: 1s
      retries: 3
      start_period: 10s
