name: dokuwiki
services:
  dokuwiki:
    container_name: dokuwiki
    image: dokuwiki/dokuwiki:2025-05-14a # other tags: master, <date> or <codename>
    user: "1000:1000" # adjust to your required user id
    ports:
      - "8080:8080" # internal port is 8080, map to what you need
    environment:
      PHP_TIMEZONE: Europe/Berlin
      #PHP_MEMORYLIMIT: 256M
      #PHP_UPLOADLIMIT: 128M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m
      timeout: 1s
      retries: 3
    volumes:
      - ./storage:/storage
