# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    container_name: mongo
    image: mongo:6.0.4-focal
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./data/mongodb_data:/data/db

  mongo-express:
    container_name: mongo-express
    image: mongo-express:1.0.0-alpha.4
    depends_on:
      - mongo
    ports:
      - 28018:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
