version: "3.8"
name: haproxy
services:
  haproxy:
    image: haproxy:3.1.6-alpine3.21
    command: sh -c "apk add --no-cache curl && mkdir /var/lib/haproxy && haproxy -f /usr/local/etc/haproxy/haproxy.cfg"
    volumes:
      - "./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
