version: "3"
services:
  #Nginx Service
  webserver:
    image: nginx:1.29.0-alpine3.22
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
