version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:2.522-jdk21
    container_name: "jenkins"
    privileged: true
    restart: always
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      # - /home/${myname}/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
