name: vault
services:
  vault-server:
    container_name: vault
    image: hashicorp/vault:1.21.0
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "vault-plaintext-root-token"
    cap_add:
      - IPC_LOCK
    healthcheck:
      test: nc -zv 0.0.0.0 8200
      interval: 1m
      timeout: 1s
      retries: 5
