input {
  gelf {
    port => 12201
    type => "gelf"
  }
  beats {
    port => 5044
  }
  tcp {
    port => 5000
    codec => "json_lines"
  }
}

filter {
  if [type] == "gelf" {
    mutate {
      add_field => { "index_suffix" => "docker-logs" }
    }
  } else if [@metadata][beat] {
    mutate {
      add_field => { "index_suffix" => "beats" }
    }
  } else {
    mutate {
      add_field => { "index_suffix" => "spring-logs" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{index_suffix}-%{+YYYY.MM.dd}"
  }
}
