version: "3.8"
name: flink
services:
  flink-jobmanager:
    image: flink:2.0.0
    container_name: flink-jobmanager
    ports:
      - "8081:8081" # Flink UI
      - "6123:6123" # RPC Port
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    command: jobmanager
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081 || exit 1"]
      interval: 1m
      timeout: 1s
      retries: 3
    networks:
      - eventhub-net

  flink-taskmanager:
    image: flink:2.0.0
    container_name: flink-taskmanager
    depends_on:
      - flink-jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    command: taskmanager
    healthcheck:
      test: ["CMD", "curl", "-f", "http://flink-jobmanager:8081/taskmanagers"]
      interval: 1m
      timeout: 1s
      retries: 3
    networks:
      - eventhub-net

networks:
  eventhub-net:
    driver: bridge
