name: cassandra
services:
  cassandra-0:
    container_name: cassandra-0
    image: cassandra:5.0.5-jammy
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_SEEDS=cassandra-0,cassandra-1
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      start_period: 60s
      interval: 1m
      timeout: 1s
      retries: 3
    networks:
      - cassandra-network
  cassandra-1:
    container_name: cassandra-1
    image: cassandra:5.0.5-jammy
    environment:
      - CASSANDRA_SEEDS=cassandra-0,cassandra-1
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      start_period: 60s
      interval: 1m
      timeout: 1s
      retries: 3
    networks:
      - cassandra-network

networks:
  cassandra-network:
    driver: bridge
