version: "3.8"
services:
  httpd:
    image: httpd:2.4.59-alpine3.20
    container_name: apache
    ports:
      - "80:80"
    volumes:
      - "/apache:/usr/local/apache2/htdocs/"
    restart: always
